
sudo: required
dist: precise

git:
  depth: 3
  submodules: true

language: cpp

env:
  matrix:
    - GCC='4.6'
    - GCC='4.9'
    - GCC='5'
    - GCC='6'
  
    - CLANG=''
    - CLANG='3.6'
    - CLANG='3.7'
    - CLANG='3.8'
    - CLANG='3.9'
    - CLANG='4.0'
    - CLANG='5.0'

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - george-edison55-precise-backports #cmake-3.1-3
        packages:
          - cmake-data
          - cmake
    - compiler: gcc-4.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++4.6            
      env:
        - MATRIX_EVAL="CC=gcc-4.6 && CXX=g++4.6"
    - compiler: gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9            
      env:
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++4.9"
    - compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5            
      env:
          - MATRIX_EVAL="CC=gcc-5 && CXX=g++5"
    - compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - automake
      env:
          - MATRIX_EVAL="CC=gcc-6 && CXX=g++6"
    - compiler: clang-3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6            
      env:
          - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++3.6"
    - compiler: clang-3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - automake
      env:
           - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++3.7"
    - compiler: clang-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8            
      env:
          - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++3.8"
    - compiler: clang-3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9            
      env:
          - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++3.9"
    - compiler: clang-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0            
      env:
          - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++4.0"
    - compiler: clang-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0            
      env:
          - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++5.0"
  allow_failures:
      - compiler: gcc-4.6
      - compiler: gcc-4.9
  fast_finish: true



before-install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls
  - sudo apt-get install -qq libgtest-dev

install:
  - cd /usr/src/gtest  
  - sudo cmake .
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - cd ${TRAVIS_BUILD_DIR}

script:
  - ls
  - g++ --version
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - echo "Compiler:" $COMP_XX
  - make VERBOSE=1
  - ./dtl_test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
email: false
