
sudo: required
dist: precise

git:
  depth: 3
  submodules: true

language: cpp

compiler:
    - 'g++-4.6'
    - 'g++-4.9'
    - 'g++-5'
    - 'g++-6'

env:
  matrix:
    - CLANG=''
    - CLANG='clang-3.6'
    - CLANG='clang-3.7'
    - CLANG='clang-3.8'
    - CLANG='clang-3.9'
    - CLANG='clang-4.0'
    - CLANG='clang-5.0'

addons:
  apt:
    sources:
      - george-edison55-precise-backports #cmake-3.1-3
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - ${compiler}

matrix:
  allow_failures:
      - compiler: '4.6'
      - compiler: '4.9'
  fast_finish: true



before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls
  - sudo apt-get install -qq libgtest-dev

install:
  - cd /usr/src/gtest  
  - sudo cmake .
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - cd ${TRAVIS_BUILD_DIR}

script:
  - ls
  - g++ --version
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - echo "Compiler:" $COMP_XX
  - make VERBOSE=1
  - ./dtl_test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
email: false
